# Generated by Django 5.0.1 on 2024-01-24 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commentator", "0004_comment_image_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="home_page",
        ),
        migrations.RemoveField(
            model_name="post",
            name="home_page",
        ),
    ]
